apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-stilling-eksport
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: internal/isAlive
    initialDelay: 20
  readiness:
    path: internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
#  vault:
#    enabled: true
#  webproxy: true
  prometheus:
    enabled: true
    path: actuator/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - name: pam-eures-eksport
        type: POSTGRES_14
        tier: "{{ cloudsql_tier }}"
        diskType: SSD
        highAvailability: true
        diskSize: 50
        diskAutoresize: true
        autoBackupTime: "03:30"
        databases:
          - name: pameuresexp
            envVarPrefix: DB
        cascadingDelete: false
#  filesFrom:
#    - secret: pam-eures-stilling-eksport-env-secret
#      mountPath: /var/run/secrets/nais.io/vault
  accessPolicy:
    outbound:
      rules:
        - application: pam-ad
        - application: pam-internal-search-api
  kafka:
    pool: {{kafka_pool}}