apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pam-eures-stilling-eksport
  namespace: teampam
  labels:
    team: teampam
spec:
  port: 8080
  liveness:
    path: internal/isAlive
    initialDelay: 20
  readiness:
    path: internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1200Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      rules:
        - application: pam-geografi
