dbnavn: pam-eures-stillingeksport-dev
internalad-search-api:
  url: https://pam-internal-search-api.nais.oera.no
spring:
  datasource:
    url: jdbc:postgresql://b27dbvl009.preprod.local:5432/${dbnavn}
