management:
  endpoint.health.enabled: true
  endpoints:
    prometheus.enabled: true
    prometheus.web.enabled: true
    web.exposure.include: health,info,status,metrics,prometheus,configprops,env,beans,mappings
  metrics:
    web.server.auto-time-requests: true
    distribution.percentiles-histogram.http.server.requests: true
    distribution.percentiles-histogram.http.client.requests: true
  health:
    elasticsearch:
      enabled: false
spring:
  metrics.web.server.auto-time-requests: true
  task.scheduling.pool.size: 5
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  profiles:
    active: ${NAIS_CLUSTER_NAME:dev}
  datasource:
    driverClassName: org.postgresql.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  servlet:
    context-path: /

internalad-search-api:
  url: http://pam-internal-search-api.default
pam-ad:
  url: http://pam-ad.default/api/v1/ads
vault:
  dbcreds.url: https://vault.adeo.no/v1/postgresql/preprod-fss/static-creds/pam-eures-stillingeksport-prod-static-admin
  auth.url: https://vault.adeo.no/v1/auth/kubernetes/preprod/sbs/login
