dbnavn: ${DB_DATABASE}
internalad-search-api:
  url: http://pam-internal-search-api
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}
