pam-ad:
  url: http://pam-ad.default.svc.nais.local:80/api/v1/ads
dbnavn: pam-eures-stillingeksport-prod
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://A01DBVL010.adeo.no:5432/${dbnavn}
    driverClassName: org.postgresql.Driver
