management:
  endpoint.health.enabled: true
  endpoints:
    prometheus.enabled: true
    prometheus.web.enabled: true
    web.exposure.include: health,info,status,metrics,prometheus,configprops,env,conditions,beans,auditevents,mappings
  metrics:
    web.server.auto-time-requests: true
    distribution.percentiles-histogram.http.server.requests: true

spring:
  metrics.web.server.auto-time-requests: true
  main:
    banner-mode: "off"
  profiles:
    active: ${NAIS_CLUSTER_NAME}
  h2:
    console:
      enabled: true
      path: /internal/h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:stillingdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 20000

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  servlet:
    context-path: /
