pam-ad:
  url: http://pam-ad.default.svc.nais.local:80/api/v1/ads
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:oracle:thin:@a30dbfl005.oera.no:1521/pameuresexp
    driverClassName: oracle.jdbc.driver.OracleDriver
