management:
  endpoint.health.enabled: true
  endpoints:
    prometheus.enabled: true
    prometheus.web.enabled: true
    web.exposure.include: health,info,status,metrics,prometheus,configprops,env,beans,mappings
  metrics:
    web.server.auto-time-requests: true
    distribution.percentiles-histogram.http.server.requests: true
    distribution.percentiles-histogram.http.client.requests: true
  health:
    elasticsearch:
      enabled: false
spring:
  metrics.web.server.auto-time-requests: true
  task.scheduling.pool.size: 5
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  profiles:
    active: ${NAIS_CLUSTER_NAME:dev}
  datasource:
    driverClassName: org.postgresql.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  servlet:
    context-path: /

kafka:
  bootstrapServers: ${KAFKA_BROKERS:localhost}
  securityProtocol: SSL
  registryUser: ${KAFKA_SCHEMA_REGISTRY_USER:user}
  registryPassword: ${KAFKA_SCHEMA_REGISTRY_PASSWORD:pwd}
  certificate: ${KAFKA_CERTIFICATE:cert}
  certificatePath: ${KAFKA_CERTIFICATE_PATH:/dev/zero}
  privateKey: ${KAFKA_PRIVATE_KEY:key}
  privateKeyPath: ${KAFKA_PRIVATE_KEY_PATH:/dev/zero}
  ca: ${KAFKA_CA:ca}
  caPath: ${KAFKA_CA_PATH}
  keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
  credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
  inboundGroupId: pam-eures-stilling-eksport-1
  inboundTopic: teampam.stilling-intern-1