name: deploy-prod
on:
  release:
    types: [published]

jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v2
    with:
      NAIS_RESOURCE: naiserator.yml,topic.yaml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

